### ISSUE TITLE
BART models not working

### ISSUE THREAD

**Issue by mooijtech** [nlpodyssey/cybertron#22]
Hello,

I am unable to use any of the BART models, I'm getting the following:
```bash
panic: runtime error: slice bounds out of range [:768] with capacity 0

goroutine 1 [running]:
github.com/nlpodyssey/cybertron/pkg/converter/bart.Convert[...]({0xc000028900, 0x19}, 0x0)
	/home/bot/Documents/2023/cybertron/pkg/converter/bart/convert.go:99 +0x1471
github.com/nlpodyssey/cybertron/pkg/converter.Convert[...]({0xc000028900, 0x19}, 0x15)
	/home/bot/Documents/2023/cybertron/pkg/converter/converter.go:33 +0x175
github.com/nlpodyssey/cybertron/pkg/tasks.loader[...].convert(0xcc49c0)
	/home/bot/Documents/2023/cybertron/pkg/tasks/loader.go:278 +0x158
github.com/nlpodyssey/cybertron/pkg/tasks.loader[...].load(0xcc49c0)
	/home/bot/Documents/2023/cybertron/pkg/tasks/loader.go:91 +0x15c
github.com/nlpodyssey/cybertron/pkg/tasks.Load[...](...)
	/home/bot/Documents/2023/cybertron/pkg/tasks/loader.go:44
main.main()
	/home/bot/Documents/2023/cybertron/examples/textgeneration/main.go:28 +0x1b2
```

**Comment by matteo-grella** [comment]
What model are you trying to use exactly and with what command?

**Comment by mooijtech** [comment]
My bad I was trying to use `facebook/bart-large` for the task `textgeneration` which is unsupported.
