### ISSUE TITLE
Failed to serialize models/vblagoje/bart_lfqa/spago_model.bin

### ISSUE THREAD

**Issue by ior308** [nlpodyssey/cybertron#29]
During serialization I got:

{"level":"trace","parameter":"model.encoder.embed_positions.weight","time":"2023-08-20T19:17:26+02:00","message":"parameter not mapped"}
Serializing model to "models/vblagoje/bart_lfqa/spago_model.bin"... unexpected fault address 0x7fc741a88000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7fc741a88000 pc=0x46b192]

goroutine 20 [running]:
runtime.throw({0xba0603?, 0xc194ec9ba8?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc194ec9b68 sp=0xc194ec9b38 pc=0x4378fd
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:838 +0x125 fp=0xc194ec9bc8 sp=0xc194ec9b68 pc=0x44da85
runtime.memmove()
        /usr/local/go/src/runtime/memmove_amd64.s:373 +0x432 fp=0xc194ec9bd0 sp=0xc194ec9bc8 pc=0x46b192
github.com/dgraph-io/badger/v3/table.(*buildData).Copy(0xc194ec9cc8, {0x7fc7416fe000, 0x8cf3df, 0x8cf3df})
        /root/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.2/table/builder.go:411 +0xb4 fp=0xc194ec9c28 sp=0xc194ec9bd0 pc=0x93b694
github.com/dgraph-io/badger/v3/table.CreateTable({0xc055aba1c0, 0x38}, 0xc194eaa5a0)
        /root/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.2/table/table.go:268 +0x1f2 fp=0xc194ec9d90 sp=0xc194ec9c28 pc=0x940512
github.com/dgraph-io/badger/v3.(*DB).handleFlushTask(0xc0001b0480, {0xc000003800?, {0x0?, 0x0?, 0x0?}})
        /root/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.2/db.go:1062 +0x232 fp=0xc194ec9ef8 sp=0xc194ec9d90 pc=0x95d252
github.com/dgraph-io/badger/v3.(*DB).flushMemtable(0xc0001b0480, 0x0?)
        /root/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.2/db.go:1084 +0x214 fp=0xc194ec9fc0 sp=0xc194ec9ef8 pc=0x95d694
github.com/dgraph-io/badger/v3.Open.func5()
        /root/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.2/db.go:357 +0x25 fp=0xc194ec9fe0 sp=0xc194ec9fc0 pc=0x958a25
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc194ec9fe8 sp=0xc194ec9fe0 pc=0x469ea1
created by github.com/dgraph-io/badger/v3.Open
        /root/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.2/db.go:356 +0x106e

**Comment by matteo-grella** [comment]
Thank you, I am on it

**Comment by ior308** [comment]
Dear Matteo, any news ?

**Comment by matteo-grella** [comment]
Hello @ior308 can you update to the latest version and give it a try?

Thank you!
